#!/usr/bin/env sh
mono sim.exe \
-N 8 \
-output ./all.dat \
-mem2.channel_max 1 \
-mem2.rank_max 1 \
-mem.channel_max 1 \
-mem.rank_max 1 \
-mem2.map_type ROW_COL_RANK_BANK_CHAN \
-mem.map_type ROW_COL_RANK_BANK_CHAN \
-sched.is_omniscient true \
-proc.wb true \
-proc.cache true \
-proc.cache_replacement_policy DRAMTrueLRU \
-proc.cache_insertion_policy All \
-proc.cache_write_policy WriteBack \
-sched.sched_algo FRFCFS \
-mctrl.page_randomize true \
-sim_type INST \
-sim_inst_max 500000000 \
-warmup_inst_max 500000000 \
-TraceDirs ./FilteredTrace \
-traces cpu2006-mcf.gz cpu2006-soplex.gz cpu2006-milc.gz cpu2006-omnetpp.gz cpu2006-leslie3d.gz redis-ycsb-workloada.gz redis-ycsb-workloadb.gz cpu2006-astar.gz&
